name: test

on:
  push:
    branches:
      - master
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install blosc
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libblosc1
      - name: Install blosc
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
        run: pip install --no-input --user blosc
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Maven Test
        run: |
          set PATH=%AppData%\Python\bin;%PATH%
          mvn -B clean test --file pom.xml
